### ISSUE TITLE
Are you willing to pins this repo in the organization's homepage?

### ISSUE THREAD

**Issue by zyyv** [unplugin/unplugin-starter#24]
### Describe the bug

On the homepage, pins some popular repos now. But this starting template is equally important for upcoming developers.

### Reproduction

none

### System Info

```Shell
none
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Currently, we didn't pin any repo, but just let GitHub suggest popular. I would prefer to keep it as-is, otherwise, it's also tricky to decide which repos to pin. Also, I think this starter template is not very relevant to end-users. As a plugin author, it's not hard to find this repo as it has been linked in many places.
